# Generated by Django 5.2.5 on 2025-10-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupregistration',
            name='confirm_password',
        ),
        migrations.RemoveField(
            model_name='signupregistration',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='signupregistration',
            name='username',
        ),
    ]
